<?php

declare(strict_types=1);

namespace Nowo\WikiBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration tree for WikiBundle.
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_wiki';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('user_class')
                    ->info('FQCN of the application user entity.')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->example('App\\Entity\\User')
                ->end()
                ->scalarNode('table_prefix')
                    ->defaultValue('wiki_')
                    ->cannotBeEmpty()
                ->end()
                ->enumNode('space_scope')
                    ->values(['team', 'user'])
                    ->defaultValue('team')
                ->end()
                ->scalarNode('team_membership_resolver')
                    ->defaultNull()
                ->end()
                ->arrayNode('database')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('driver')->defaultValue('doctrine_orm')->end()
                        ->scalarNode('platform')->defaultValue('mysql')->end()
                        ->scalarNode('entity_manager')->defaultValue('default')->end()
                    ->end()
                ->end()
                ->scalarNode('route_prefix')
                    ->defaultValue('')
                ->end()
                ->scalarNode('dashboard_route')
                    ->defaultNull()
                ->end()
                ->arrayNode('editor')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('tiptap_config')->defaultValue('notion')->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('access_checker')->defaultNull()->end()
                        ->arrayNode('admin_roles')->scalarPrototype()->end()->defaultValue(['ROLE_ADMIN'])->end()
                        ->arrayNode('access_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('list_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('create_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('edit_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('history_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('archive_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('ai_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                        ->arrayNode('import_roles')->scalarPrototype()->end()->defaultValue(['ROLE_ADMIN'])->end()
                        ->arrayNode('export_roles')->scalarPrototype()->end()->defaultValue(['ROLE_USER'])->end()
                    ->end()
                ->end()
                ->arrayNode('import_export')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->integerNode('max_upload_bytes')->defaultValue(52428800)->min(1048576)->max(524288000)->end()
                    ->end()
                ->end()
                ->arrayNode('ai')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->scalarNode('agent')->defaultValue('wiki_assistant')->cannotBeEmpty()->end()
                        ->booleanNode('context_injection')->defaultTrue()->info('Inject search hits into the system prompt (in addition to optional agent tools).')->end()
                        ->integerNode('max_context_pages')->defaultValue(8)->min(1)->max(25)->end()
                        ->integerNode('max_context_chars')->defaultValue(12000)->min(1000)->max(100000)->end()
                        ->scalarNode('system_prompt')->defaultNull()->end()
                    ->end()
                ->end()
                ->arrayNode('routes')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('index')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_index')->end()
                        ->end()->end()
                        ->arrayNode('space')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_space')->end()
                        ->end()->end()
                        ->arrayNode('page_view')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/pages/{pageSlug}')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_page_view')->end()
                        ->end()->end()
                        ->arrayNode('page_edit')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/pages/{pageSlug}/edit')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_page_edit')->end()
                        ->end()->end()
                        ->arrayNode('page_new')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/pages/new')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_page_new')->end()
                        ->end()->end()
                        ->arrayNode('page_history')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/pages/{pageSlug}/history')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_page_history')->end()
                        ->end()->end()
                        ->arrayNode('page_diff')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/pages/{pageSlug}/diff')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_page_diff')->end()
                        ->end()->end()
                        ->arrayNode('page_archive')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/pages/{pageSlug}/archive')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_page_archive')->end()
                        ->end()->end()
                        ->arrayNode('search')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/search')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_search')->end()
                        ->end()->end()
                        ->arrayNode('ai_ask')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/ask')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_ai_ask')->end()
                        ->end()->end()
                        ->arrayNode('space_export')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/export')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_space_export')->end()
                        ->end()->end()
                        ->arrayNode('space_import')->addDefaultsIfNotSet()->children()
                            ->scalarNode('path')->defaultValue('/tools/wiki/spaces/{spaceSlug}/import')->end()
                            ->scalarNode('name')->defaultValue('nowo_wiki_space_import')->end()
                        ->end()->end()
                    ->end()
                ->end()
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('layout')->defaultValue('@NowoWikiBundle/layout.html.twig')->end()
                        ->scalarNode('index')->defaultValue('@NowoWikiBundle/manage/index.html.twig')->end()
                        ->scalarNode('space')->defaultValue('@NowoWikiBundle/manage/space.html.twig')->end()
                        ->scalarNode('page_view')->defaultValue('@NowoWikiBundle/manage/page_view.html.twig')->end()
                        ->scalarNode('page_edit')->defaultValue('@NowoWikiBundle/manage/page_edit.html.twig')->end()
                        ->scalarNode('page_history')->defaultValue('@NowoWikiBundle/manage/page_history.html.twig')->end()
                        ->scalarNode('page_diff')->defaultValue('@NowoWikiBundle/manage/page_diff.html.twig')->end()
                        ->scalarNode('search')->defaultValue('@NowoWikiBundle/manage/search.html.twig')->end()
                        ->scalarNode('ai_ask')->defaultValue('@NowoWikiBundle/manage/ai_ask.html.twig')->end()
                    ->end()
                ->end()
                ->scalarNode('firewall')
                    ->defaultValue('main')
                ->end()
            ->end();

        return $treeBuilder;
    }
}
